---

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-json
        exclude: devcontainer.json
      - id: check-yaml
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: detect-private-key

  - repo: https://github.com/bridgecrewio/checkov.git
    rev: '2.3.115'
    hooks:
      - id: checkov
        verbose: false
        args: [ ]

  - repo: https://github.com/antonbabenko/pre-commit-terraform
  # Get the latest from:
  # https://github.com/antonbabenko/pre-commit-terraform/releases
    rev: v1.77.1
    hooks:
      - id: terraform_fmt
      # - id: terraform_validate
      # - id: terraform_tfsec
      - id: terraform_tflint
      - id: terrascan
        args:
          - --args=--non-recursive
          - --args=--skip-rules="AC_AZURE_0356" # avoids nsg test for simple admin_password example
          - --args=--skip-rules="AC_AZURE_0389" # skip "Ensure that Azure Resource Group has resource lock enabled"
          - --args=--policy-type=azure
          - --args=--verbose

  # - repo: https://github.com/tenable/terrascan
  #   rev: v1.16.0
  #   hooks:
  #     - id: terraform-pre-commit
  #       args: ["-i terraform -c terrascan_config.toml"]

  # - repo: https://github.com/terraform-docs/terraform-docs
  #   rev: "v0.16.0"
  #   hooks:
  #     - id: terraform-docs-go
  #       args: ["markdown", "table", "--output-file", "README.md", "./"]